name: generate

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    paths:
      - ".github/workflows/generate.yml"
      - "commit"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check
        run: |
          rm -rf tree-sitter-latex
          git clone --depth=1 https://github.com/latex-lsp/tree-sitter-latex.git
          cd tree-sitter-latex
          if diff -q ../commit <(git rev-parse HEAD); then
            echo "No changes in upstream."
            echo "donext=0" >> $GITHUB_OUTPUT
          else
            git rev-parse HEAD > ../commit
            rm -rf .git
            rm .gitignore
            echo "donext=1" >> $GITHUB_OUTPUT
          fi
      - uses: tree-sitter/setup-action@v2
        if: ( steps.check.outputs.donext == 1 )
      - name: Generate
        if: ( steps.check.outputs.donext == 1 )
        run: |
          cd tree-sitter-latex
          tree-sitter generate --abi 15 src/grammar.json
      - name: Commit and push changes
        if: ( steps.check.outputs.donext == 1 )
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "$(date -uIs)"
          git push
